### ISSUE TITLE
Great package - little change necessary for msgraph_auth to work

### ISSUE THREAD

**Issue by matbmeijer** [davidski/msgraphr#1]
Hi David,

first of all, thank you very much for this simple but powerful package - has helped me a lot to get the authentication logic of Microsoft graph. I have noticed some necessary changes for the function ```msgraphr::msgraph_auth()```. The `app_name has to be passed as one of the function variables to be able to execute the function with other apps. 
```r
msgraph_auth <- function(client_id, client_secret, app_name) {
...
}
```

**Comment by davidski** [comment]
Thanks for the report! I need to poke at this a bit. The application name _shouldn't_ be necessary, but let me look into this.

**Comment by davidski** [comment]
Hi, @matbmeijer! I've not been able to reproduce this problem. Can you say more about the error you were getting before you introduced the `app_name` change? The application name shouldn't matter for authing into the Graph API, and `app_name` gets set to a hard-coded value in the auth flow.

If you can provide the flow you were doing, I'll continue to track this down!

**Comment by matbmeijer** [comment]
Hi David, you're right - my error comes from `msgraphr:::msgraph_token()`. The error returning is `Error in msgraphr:::msgraph_token() : MSGRAPH token not found.FALSE`. It's reacting as the formula prescribes:
```r
{
    token <- Sys.getenv("MSGRAPH_PAT", "")
    if (token == "") 
        stop("MSGRAPH token not found.", .call = FALSE)
    else token
}
```
What do you mean when you say "_Set MSGRAPH_PAT to a location for saving the Oauth2.0 token_" in your README file? If I delete the `cache = msgraph_token()`from the `msgraph_auth`function it works, but if I don't, it does not - whatever I do. I am sure I am missing something. Thank you!

**Comment by davidski** [comment]
Ah! That's poorly documented. MSGRAPH_PAT is an environment variable that points to a file location (ideally, full qualified) for `httr` to cache OAuth tokens. I've updated the docs, made that an optional setting (will default to the current working directory and emit a warning), and pushed that change. Please update and try again!

**Comment by matbmeijer** [comment]
Hi David, just tested it! Works now like a charm, both if MSGRAPH_PAT are defined in the environment or not. Thank you very much for solving it so fast!
