### ISSUE TITLE
Update readme file to extract id correctly from table

### ISSUE THREAD

**Issue by matbmeijer** [davidski/msgraphr#2]
Hi David,

On your README file I wanted to propose the following change:
```r
get_sites(search = "", token) %>% head(1) %>% pull(site_id) -> my_site
````
Instead of:
```r
get_sites(search = "", token) %>% head(1) %>% pull(id) -> my_site
```

At least for me, the returned `data.frame` contains the column `id`instead of `site_id`

Thank you very much for the effort, great package!

**Comment by davidski** [comment]
Thanks for the catch! Checked and corrected!
