### ISSUE TITLE
Suggestion - flatten data.frames returned from get_list_entries and get_lists

### ISSUE THREAD

**Issue by matbmeijer** [davidski/msgraphr#3]
Hi David,

Not real issues but much more enhancements. I would suggest to use the function `jsonlite::flatten(recursive = TRUE)` for the functions `get_lists` and the function `get_list_entries`.

Last but not least, I would suggest to clean to column names from the obtained names, as they contain signs as @ (e.g. column `@odata.etag`)

**Comment by davidski** [comment]
`get_list_entries` cleans the returned names both with `janitor::clean_names()` and with some explicit `gsub()` filtering. Both `get_list_entries()` and `get_lists()` do some deep indexing and should return flat dataframes for most list types. I'm torn on whether to flatten or not, as that's a design trade off between a more opinionated API and perhaps more fragile vs. a straight wrapper around the API, similar to r-lib/gh. Willing to be convinced here. :smile:

**Comment by matbmeijer** [comment]
Hi David,
In my case it returned a list of lists data.frame - but I understand the point about not removing data which might be useful. In my  specific case I was able to flatten without loosing any information
